name: Test and deploy

on:
  push:
    branches:
      - main
      
  workflow_dispatch:


jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Set environment variable from secret
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
        run: |
          echo "COVERALLS_REPO_TOKEN=$COVERALLS_REPO_TOKEN" >> $GITHUB_ENV
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile
      
      - name: Debug repo-token
        run: echo $COVERALLS_REPO_TOKEN

      - name: Run tests
        run:  pnpm coverage

      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GH_TOKEN }}
          path-to-lcov: coverage/lcov.info
          git-branch: main
          debug: true
      
  build:
    name: Build docs
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile
      
      - name: Build lib
        run: pnpm build

      - name: Build docs
        run: pnpm docs:build

      - name: Upload docs
        uses: actions/upload-artifact@v3
        with:
          name: docs
          path: ./docs/.vitepress/dist

  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download docs
        uses: actions/download-artifact@v3
        with:
          name: docs

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          publish_dir: .
